[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_lend_borrow = "38mFsa4ZPpRLugnbySeAurd6cKcbTP91c8YzswqdzjK5"

[toolchain]
anchor_version = "0.30.1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
